service: kubernetes-alerting-lambda-example

plugins:
  - serverless-pseudo-parameters
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3

package:
  individually: true
  exclude:
    - ./**

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "eu-central-1"}
  memorySize: 128
  timeout: 30
  versionFunctions: true
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
    apiKeySourceType: HEADER
    apiKeys:
      - ${self:service}-api-key
  tracing:
    apiGateway: false
    lambda: false
  logRetentionInDays: 1
  endpointType: Edge

functions:
  api:
    handler: bin/api
    package:
      include:
        - ./bin/api
    description: Kubernetes API utils
    role: serverless
    events:
      - http:
          path: /repair
          method: POST
          private: true
    environment:
      REGION: ${opt:region, "eu-central-1"}
      CLUSTER_NAME: ${opt:cluster}

resources:
  Resources:
    serverless:
      Type: AWS::IAM::Role
      Properties:
        RoleName: serverless
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service:
                  - lambda.amazonaws.com
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                AWS:
                  !Join [
                    ":",
                    ["arn:aws:iam:", { Ref: "AWS::AccountId" }, "root"],
                  ]
        Policies:
          - PolicyName: ilert-kube-agent
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:CreateLogGroup
                  Resource: "*"
                - Effect: Allow
                  Action: logs:PutLogEvents
                  Resource:
                    !Join [
                      ":",
                      [
                        "arn:aws:logs",
                        { "Ref": "AWS::Region" },
                        { Ref: "AWS::AccountId" },
                        "log-group",
                        "/aws/lambda/ilert-kube-agent-serverless*",
                      ],
                    ]
                - Effect: Allow
                  Action: eks:*
                  Resource: "*"
